image: docker:latest

services:
    - docker:dind

before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build-master:
    stage: build
    variables:
        IMAGE_TAG: "$CI_REGISTRY_IMAGE/php-caddy"
    script:
        - docker build --pull -t $IMAGE_TAG ./registry
        - docker push $IMAGE_TAG
    only:
        - master
