image: docker:latest

services:
    - docker:dind

before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build-master:
    stage: build
    variables:
        IMAGE_TAG: "$CI_REGISTRY_IMAGE/php-caddy"
    script:
        - echo "The image tag is $IMAGE_TAG"
        - docker build --pull -t $IMAGE_TAG ./registry
        - docker push $IMAGE_TAG
    only:
        - master

build-tag:
    stage: build
    only:
        - tags
    variables:
        IMAGE_TAG: $CI_REGISTRY_IMAGE/php-caddy:$CI_COMMIT_TAG
    script:
        - echo "The image tag is $IMAGE_TAG"
        - docker build --pull -t $IMAGE_TAG ./registry
        - docker push $IMAGE_TAG
