version: "3"
services:
  app:
    image: cakephp-app
    container_name: cakephp-app
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 8888:80
    volumes:
      - .:/srv/cakephp

  cake:
    image: cakephp-app
    container_name: cakephp-console
    depends_on:
      - app
    volumes:
      - .:/srv/cakephp
    entrypoint: [
      "/srv/cakephp/app/Console/cake",
      "-app", '/srv/cakephp/app'
    ]