version: "3"
services:
    app:
        build:
            context: .
            dockerfile: docker/Dockerfile
        ports:
            - 8080:80
        volumes:
            - .:/srv/app
        environment:
            CADDY_HOSTNAME: "example.com" #Remember add it in host file
