version: "3"
services:
    app:
        build:
            context: .
            dockerfile: docker/Dockerfile
        ports:
            - 2015:2015
        volumes:
            - .:/srv/app
        environment:
            CADDY_HOSTNAME: "example.com"
